# Generated by Django 5.2.1 on 2025-05-25 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('data_protection_officer', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('controller', 'Controller'), ('processor', 'Processor')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('data_categories', models.TextField(help_text='List of data categories (e.g. name, email, health data, etc.)')),
                ('data_subject_categories', models.TextField(help_text='Categories of data subjects (e.g. employees, customers, etc.)')),
                ('recipients', models.TextField(blank=True, null=True)),
                ('third_country_transfers', models.TextField(blank=True, null=True)),
                ('retention_period', models.CharField(blank=True, max_length=255, null=True)),
                ('security_measures', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_activities', to='ropa.organization')),
            ],
        ),
    ]
