# Generated by Django 5.2.1 on 2025-05-25 15:38

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='role',
        ),
        migrations.AddField(
            model_name='organization',
            name='country',
            field=django_countries.fields.CountryField(default='select country', max_length=2),
            preserve_default=False,
        ),
    ]
