# Generated by Django 5.2.1 on 2025-05-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0002_remove_organization_role_organization_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSubjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('employees', 'Employees'), ('customers', 'Customers'), ('suppliers', 'Suppliers'), ('website_visitors', 'Website Visitors'), ('patients', 'Patients'), ('students', 'Students'), ('other', 'Other')], max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='processingactivity',
            name='data_categories',
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='ata_subject_categories',
            field=models.ManyToManyField(related_name='processing_activities', to='ropa.datasubjectcategory'),
        ),
    ]
