# Generated by Django 5.2.1 on 2025-05-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0003_datasubjectcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasubjectcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='processingactivity',
            name='ata_subject_categories',
        ),
        migrations.AddField(
            model_name='datasubjectcategory',
            name='name',
            field=models.CharField(default='enter name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='data_categories',
            field=models.TextField(default='enter categories', help_text='List of data categories (e.g. name, email, health data, etc.)'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='processingactivity',
            name='data_subject_categories',
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='data_subject_categories',
            field=models.ManyToManyField(related_name='processing_activities', to='ropa.datasubjectcategory'),
        ),
    ]
