# Generated by Django 5.2.1 on 2025-05-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0004_remove_datasubjectcategory_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='processingactivity',
            name='data_categories',
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='data_categories',
            field=models.ManyToManyField(help_text='List of data categories (e.g. name, email, health data, etc.)', to='ropa.datacategory'),
        ),
    ]
