# Generated by Django 5.2.1 on 2025-05-25 17:44

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0005_datacategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('asset_type', models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('network', 'Network Component'), ('cloud', 'Cloud Service'), ('other', 'Other')], max_length=50)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('lifecycle_status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='ropa.organization')),
            ],
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='processing_activities', to='ropa.processingasset'),
        ),
        migrations.CreateModel(
            name='ProcessingAssetLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_locations', to='ropa.organization')),
            ],
        ),
        migrations.AddField(
            model_name='processingasset',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='ropa.processingassetlocation'),
        ),
    ]
